# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ece52f48255ed07b14554911cf7ac91ecf04278c6c7038b5e10bc645e8f20a17e1bca50219e896942a03545db29360e794eefd360b3256fc28e40e784a5cf7

test:
  secret_key_base: 94906e364f9845fc363c625881f45b91a1b62ff9db4e536176e493a7cd551d345593cc312dee498f8e376e8b120570ca267add195ba6feee9141ec8ce4015d05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
